import "./globals.css";
import BarraInferior from "@/components/BarraInferior";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen bg-blue-200 text-white relative">      
          {children}       
      </body>
    </html>
  );
}
